version: '3.8'

services:
  database:
    image: postgres:11
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASS
      - POSTGRES_DB=$DATABASE_NAME
    container_name: 'postgres-for-testing'
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    tmpfs: /var/lib/postgresql/data
  app:
    depends_on:
      - database
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASS
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
