version: '3.8'

services:
  mysqldb:
    image: mariadb:10.5.8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_PASS=$DATABASE_PASS
      - DATABASE_NAME=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASS
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
